### PR TITLE
30 hit stats dump

### LINKED ISSUE #30: Support Contract Hit Stats Dump
This issue is to track adding support to export NDI Contract Stats into a CSV File. 

Ideally we will have a task as following:
```
  tasks:
    - name: get contract stats
      cisco.nd.nd_contracts_stats: 
        insights_group: SYD
        site_name: FAB1
        hitcount_by: EpgContractFilter
        file: stats.csv
```
and will dump all the statistics in csv format. 

The use case is around contract optimisation and clean up where we can easily filter this data externally to understandf which contract are getting hit and which ones aren't so that they can be removed.

### PR DESCRIPTION
**Pull request by akinross**
fixes #30

### CODE REVIEW

**Review by samiib — APPROVED** [review]
lgtm 👍

**Review by sajagana — APPROVED** [review]
LGTM!

**Review by shrsr — APPROVED** [review]
LGTM

**Review by lhercot — APPROVED** [review]
LGTM

**Pull request merged**
